"""Tax calculator models — re-exports for convenience."""

from src.models.exceptions import (
    InvalidFilingStatusError,
    MissingIncomeDataError,
    NegativeIncomeError,
    TaxCalculatorError,
    UnsupportedScenarioError,
)
from src.models.filing_status import FilingStatus
from src.models.tax_input import (
    AboveLineDeductions,
    AGIInput,
    BracketTaxInput,
    CapitalGainsTaxInput,
    CreditInput,
    FicaInput,
    GrossIncome,
    NiitInput,
    QualifiedDividendTaxInput,
    StandardDeductionInput,
)
from src.models.tax_output import (
    AGIResult,
    BracketDetail,
    BracketTaxResult,
    CapitalGainsTaxResult,
    CreditResult,
    FicaResult,
    NiitResult,
    PreferentialRateDetail,
    QualifiedDividendTaxResult,
    StandardDeductionResult,
)
from src.models.workflow_models import (
    CreditsResult,
    DeductionResult,
    FullTaxCalculationResult,
    Income1099B,
    Income1099DIV,
    Income1099INT,
    Income1099NEC,
    IncomeResult,
    ItemizedDeductions,
    TaxComputationResult,
    TaxCredits,
    TaxReturnInput,
    TaxSummary,
    W2Income,
)

__all__ = [
    "AGIInput",
    "AGIResult",
    "AboveLineDeductions",
    "BracketDetail",
    "BracketTaxInput",
    "BracketTaxResult",
    "CapitalGainsTaxInput",
    "CapitalGainsTaxResult",
    "CreditInput",
    "CreditResult",
    "CreditsResult",
    "DeductionResult",
    "FicaInput",
    "FicaResult",
    "FilingStatus",
    "FullTaxCalculationResult",
    "GrossIncome",
    "Income1099B",
    "Income1099DIV",
    "Income1099INT",
    "Income1099NEC",
    "IncomeResult",
    "InvalidFilingStatusError",
    "ItemizedDeductions",
    "MissingIncomeDataError",
    "NegativeIncomeError",
    "NiitInput",
    "NiitResult",
    "PreferentialRateDetail",
    "QualifiedDividendTaxInput",
    "QualifiedDividendTaxResult",
    "StandardDeductionInput",
    "StandardDeductionResult",
    "TaxCalculatorError",
    "TaxComputationResult",
    "TaxCredits",
    "TaxReturnInput",
    "TaxSummary",
    "UnsupportedScenarioError",
    "W2Income",
]
